repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # v5.0.0
    hooks:
      - id: check-json
      - id: end-of-file-fixer
        types: [file, python]
      - id: trailing-whitespace
        types: [file, python]
      - id: mixed-line-ending
      - id: check-added-large-files
        args: [--maxkb=4096]
  - repo: https://github.com/psf/black
    rev: 8a737e727ac5ab2f1d4cf5876720ed276dc8dc4b  # 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 0a0b7a830386ba6a31c2ec8316849ae4d1b8240d  # 6.0.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "-l", "88", "--trailing-comma", "--multi-line", "3"]
  - repo: https://github.com/pycqa/flake8.git
    rev: cf1542cefa3e766670b2066dd75c4571d682a649  # 7.1.1
    hooks:
      - id: flake8
        types: [python]
        args: ["--max-line-length", "88", "--ignore", "E203,E501,W503,W504"]
