#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Jan Sahaay AI — scheme database generator.

Builds app/schemes-data.js containing 1000+ Indian government welfare schemes:
  * Curated Central Government schemes
  * Curated flagship State schemes (with emphasis on Jharkhand)
  * State-wise implementations of Centrally Sponsored Schemes for every
    State and Union Territory (these programmes are delivered and applied
    for at the state level, so each state gets its own entry).

Scheme record (compact keys to keep the payload small):
  id   unique id
  n    name (English)          nh   name (Hindi)
  b    benefit (English)       bh   benefit (Hindi)
  lvl  "C" central | "S" state | "CSS" centrally sponsored, state implemented
  st   "ALL" or the state/UT name (English)
  tag  category tag key (see TAGS in app)
  e    eligibility dict:
         aMin/aMax  age range              g     "F"/"M"/"O" or absent (any)
         inc        max annual income ₹    cat   list of social categories
         occ        list of occupations    res   "R" rural / "U" urban
         bpl/dis/wid/preg  required flags (true = only shown when user has it)
         sow        true = SC/ST OR woman qualifies (Stand-Up India rule)
         sts        restrict to a list of states (e.g. North-East)

Occupation keys: student farmer worker salaried self_employed unemployed
                 homemaker fisher artisan street_vendor retired
Category keys:   sc st obc gen ews minority
"""

import json
import os

STATES = [
    ("Andhra Pradesh", "आंध्र प्रदेश"),
    ("Arunachal Pradesh", "अरुणाचल प्रदेश"),
    ("Assam", "असम"),
    ("Bihar", "बिहार"),
    ("Chhattisgarh", "छत्तीसगढ़"),
    ("Goa", "गोवा"),
    ("Gujarat", "गुजरात"),
    ("Haryana", "हरियाणा"),
    ("Himachal Pradesh", "हिमाचल प्रदेश"),
    ("Jharkhand", "झारखंड"),
    ("Karnataka", "कर्नाटक"),
    ("Kerala", "केरल"),
    ("Madhya Pradesh", "मध्य प्रदेश"),
    ("Maharashtra", "महाराष्ट्र"),
    ("Manipur", "मणिपुर"),
    ("Meghalaya", "मेघालय"),
    ("Mizoram", "मिज़ोरम"),
    ("Nagaland", "नागालैंड"),
    ("Odisha", "ओडिशा"),
    ("Punjab", "पंजाब"),
    ("Rajasthan", "राजस्थान"),
    ("Sikkim", "सिक्किम"),
    ("Tamil Nadu", "तमिलनाडु"),
    ("Telangana", "तेलंगाना"),
    ("Tripura", "त्रिपुरा"),
    ("Uttar Pradesh", "उत्तर प्रदेश"),
    ("Uttarakhand", "उत्तराखंड"),
    ("West Bengal", "पश्चिम बंगाल"),
    ("Andaman and Nicobar Islands", "अंडमान और निकोबार द्वीप समूह"),
    ("Chandigarh", "चंडीगढ़"),
    ("Dadra and Nagar Haveli and Daman and Diu", "दादरा और नगर हवेली और दमन और दीव"),
    ("Delhi", "दिल्ली"),
    ("Jammu and Kashmir", "जम्मू और कश्मीर"),
    ("Ladakh", "लद्दाख"),
    ("Lakshadweep", "लक्षद्वीप"),
    ("Puducherry", "पुडुचेरी"),
]

NE_STATES = ["Arunachal Pradesh", "Assam", "Manipur", "Meghalaya",
             "Mizoram", "Nagaland", "Sikkim", "Tripura"]


def S(name, name_hi, benefit, benefit_hi, tag, lvl="C", st="ALL", **e):
    return {"n": name, "nh": name_hi, "b": benefit, "bh": benefit_hi,
            "tag": tag, "lvl": lvl, "st": st, "e": e}


# --------------------------------------------------------------------------
# 1. Curated Central Government schemes (apply anywhere in India)
# --------------------------------------------------------------------------
CENTRAL = [
    # ---- Agriculture & allied ----
    S("PM-KISAN Samman Nidhi", "पीएम-किसान सम्मान निधि",
      "₹6,000 per year income support to farmer families in 3 installments",
      "किसान परिवारों को प्रति वर्ष ₹6,000 की आय सहायता, तीन किस्तों में",
      "agri", occ=["farmer"], aMin=18),
    S("PM Kisan Maandhan Yojana", "प्रधानमंत्री किसान मानधन योजना",
      "₹3,000 monthly pension to small farmers after age 60",
      "छोटे किसानों को 60 वर्ष की आयु के बाद ₹3,000 मासिक पेंशन",
      "pension", occ=["farmer"], aMin=18, aMax=40),
    S("Kisan Credit Card (KCC)", "किसान क्रेडिट कार्ड",
      "Crop loans up to ₹3 lakh at subsidised interest rates",
      "रियायती ब्याज दर पर ₹3 लाख तक का फसल ऋण",
      "agri", occ=["farmer", "fisher"], aMin=18, aMax=75),
    S("PM Fasal Bima Yojana", "प्रधानमंत्री फसल बीमा योजना",
      "Comprehensive crop insurance at a nominal premium (1.5–2%)",
      "नाममात्र प्रीमियम (1.5–2%) पर व्यापक फसल बीमा",
      "agri", occ=["farmer"], aMin=18),
    S("Soil Health Card Scheme", "मृदा स्वास्थ्य कार्ड योजना",
      "Free soil testing with fertiliser and nutrient recommendations",
      "निःशुल्क मिट्टी जांच व उर्वरक-पोषक तत्व की सिफारिशें",
      "agri", occ=["farmer"]),
    S("PM Krishi Sinchayee Yojana", "प्रधानमंत्री कृषि सिंचाई योजना",
      "Up to 55% subsidy on drip and sprinkler micro-irrigation",
      "ड्रिप व स्प्रिंकलर सूक्ष्म सिंचाई पर 55% तक अनुदान",
      "agri", occ=["farmer"], aMin=18),
    S("Paramparagat Krishi Vikas Yojana", "परम्परागत कृषि विकास योजना",
      "₹50,000 per hectare over 3 years for organic farming",
      "जैविक खेती हेतु 3 वर्षों में ₹50,000 प्रति हेक्टेयर सहायता",
      "agri", occ=["farmer"], aMin=18),
    S("PM Matsya Sampada Yojana", "प्रधानमंत्री मत्स्य संपदा योजना",
      "Up to 60% subsidy on fisheries and aquaculture projects",
      "मत्स्य पालन व जलकृषि परियोजनाओं पर 60% तक अनुदान",
      "agri", occ=["fisher", "farmer"], aMin=18),
    S("National Livestock Mission", "राष्ट्रीय पशुधन मिशन",
      "50% capital subsidy for poultry, sheep, goat and piggery units",
      "मुर्गी, भेड़, बकरी व सूअर पालन इकाइयों पर 50% पूंजी अनुदान",
      "agri", occ=["farmer", "self_employed"], aMin=18),
    S("PM-KUSUM", "पीएम-कुसुम योजना",
      "60% subsidy on standalone solar agriculture pumps",
      "स्वतंत्र सोलर कृषि पंपों पर 60% अनुदान",
      "agri", occ=["farmer"], aMin=18),
    S("PM Van Dhan Yojana", "प्रधानमंत्री वन धन योजना",
      "Value-addition training and support for tribal forest-produce gatherers",
      "वनोपज संग्राहक आदिवासियों को प्रशिक्षण व मूल्य-संवर्धन सहायता",
      "agri", cat=["st"], res="R", aMin=18),

    # ---- Health ----
    S("Ayushman Bharat PM-JAY", "आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना",
      "Free hospital treatment up to ₹5 lakh per family per year",
      "प्रति परिवार प्रति वर्ष ₹5 लाख तक निःशुल्क अस्पताल इलाज",
      "health", inc=300000),
    S("Ayushman Vay Vandana Card", "आयुष्मान वय वंदना कार्ड",
      "₹5 lakh free health cover for all citizens aged 70 and above",
      "70 वर्ष से अधिक आयु के सभी नागरिकों को ₹5 लाख निःशुल्क स्वास्थ्य कवर",
      "health", aMin=70),
    S("Janani Suraksha Yojana", "जननी सुरक्षा योजना",
      "Cash assistance of ₹600–₹1,400 for institutional delivery",
      "संस्थागत प्रसव पर ₹600–₹1,400 की नकद सहायता",
      "health", g="F", preg=True, aMin=18),
    S("PM Matru Vandana Yojana", "प्रधानमंत्री मातृ वंदना योजना",
      "₹5,000 maternity benefit for the first child; ₹6,000 if second is a girl",
      "पहले बच्चे पर ₹5,000 मातृत्व लाभ; दूसरी संतान बेटी होने पर ₹6,000",
      "wcd", g="F", preg=True, aMin=19),
    S("Rashtriya Vayoshri Yojana", "राष्ट्रीय वयोश्री योजना",
      "Free physical aids and assisted-living devices for senior citizens",
      "वरिष्ठ नागरिकों को निःशुल्क सहायक व जीवन-सहायता उपकरण",
      "health", aMin=60, bpl=True),
    S("ADIP Scheme", "एडिप योजना (दिव्यांग सहायक उपकरण)",
      "Free aids and assistive devices for persons with disabilities",
      "दिव्यांगजनों को निःशुल्क सहायक उपकरण",
      "health", dis=True, inc=300000),

    # ---- Housing, water, energy ----
    S("PM Awas Yojana – Urban 2.0", "प्रधानमंत्री आवास योजना – शहरी 2.0",
      "Housing subsidy up to ₹2.5 lakh for EWS/LIG/MIG urban families",
      "शहरी EWS/LIG/MIG परिवारों को ₹2.5 लाख तक आवास सब्सिडी",
      "housing", res="U", inc=900000, aMin=18),
    S("Swachh Bharat Mission – Toilet Incentive", "स्वच्छ भारत मिशन – शौचालय प्रोत्साहन",
      "₹12,000 incentive for building a household toilet",
      "घरेलू शौचालय निर्माण हेतु ₹12,000 प्रोत्साहन राशि",
      "housing", res="R", inc=300000),
    S("Jal Jeevan Mission", "जल जीवन मिशन",
      "Functional tap-water connection for every rural household",
      "हर ग्रामीण परिवार को क्रियाशील नल-जल कनेक्शन",
      "housing", res="R"),
    S("PM Surya Ghar Muft Bijli Yojana", "पीएम सूर्य घर मुफ्त बिजली योजना",
      "Up to ₹78,000 subsidy for rooftop solar and 300 units free power",
      "रूफटॉप सोलर पर ₹78,000 तक सब्सिडी व 300 यूनिट मुफ्त बिजली",
      "housing", aMin=18),
    S("PM Ujjwala Yojana 2.0", "प्रधानमंत्री उज्ज्वला योजना 2.0",
      "Free LPG connection with first refill and stove for poor households",
      "गरीब परिवारों को निःशुल्क एलपीजी कनेक्शन, पहली रिफिल व चूल्हा",
      "wcd", g="F", aMin=18, bpl=True),
    S("PM E-DRIVE", "पीएम ई-ड्राइव योजना",
      "Purchase subsidy on electric two-wheelers and three-wheelers",
      "इलेक्ट्रिक दो-पहिया व तीन-पहिया वाहनों की खरीद पर सब्सिडी",
      "social", aMin=18),

    # ---- Financial inclusion, insurance, pension ----
    S("PM Jan Dhan Yojana", "प्रधानमंत्री जन धन योजना",
      "Zero-balance bank account with RuPay card and ₹2 lakh accident cover",
      "जीरो बैलेंस बैंक खाता, रुपे कार्ड व ₹2 लाख दुर्घटना बीमा",
      "fin", aMin=10),
    S("Atal Pension Yojana", "अटल पेंशन योजना",
      "Guaranteed pension of ₹1,000–₹5,000 per month after age 60",
      "60 वर्ष के बाद ₹1,000–₹5,000 की गारंटीड मासिक पेंशन",
      "pension", aMin=18, aMax=40),
    S("PM Jeevan Jyoti Bima Yojana", "प्रधानमंत्री जीवन ज्योति बीमा योजना",
      "₹2 lakh life insurance cover at just ₹436 per year",
      "मात्र ₹436 वार्षिक प्रीमियम पर ₹2 लाख का जीवन बीमा",
      "ins", aMin=18, aMax=50),
    S("PM Suraksha Bima Yojana", "प्रधानमंत्री सुरक्षा बीमा योजना",
      "₹2 lakh accident insurance cover at just ₹20 per year",
      "मात्र ₹20 वार्षिक प्रीमियम पर ₹2 लाख का दुर्घटना बीमा",
      "ins", aMin=18, aMax=70),
    S("Sukanya Samriddhi Yojana", "सुकन्या समृद्धि योजना",
      "High-interest tax-free savings account for a girl child below 10",
      "10 वर्ष से छोटी बेटी हेतु उच्च ब्याज, कर-मुक्त बचत खाता",
      "wcd", aMin=18),
    S("Mahila Samman Savings Certificate", "महिला सम्मान बचत पत्र",
      "7.5% interest savings scheme exclusively for women",
      "महिलाओं हेतु 7.5% ब्याज वाली विशेष बचत योजना",
      "fin", g="F"),
    S("Senior Citizen Savings Scheme", "वरिष्ठ नागरिक बचत योजना",
      "High-interest (8%+) government savings scheme for citizens 60+",
      "60+ नागरिकों हेतु उच्च ब्याज (8%+) सरकारी बचत योजना",
      "fin", aMin=60),

    # ---- Food security ----
    S("PM Garib Kalyan Anna Yojana", "प्रधानमंत्री गरीब कल्याण अन्न योजना",
      "Free foodgrains every month to ration-card families",
      "राशन कार्ड धारक परिवारों को हर माह निःशुल्क खाद्यान्न",
      "food", inc=250000),
    S("Antyodaya Anna Yojana", "अंत्योदय अन्न योजना",
      "35 kg highly subsidised foodgrains monthly for the poorest families",
      "सबसे गरीब परिवारों को 35 किलो अत्यधिक रियायती खाद्यान्न प्रतिमाह",
      "food", bpl=True),

    # ---- Business, self-employment ----
    S("PM Mudra Yojana", "प्रधानमंत्री मुद्रा योजना",
      "Collateral-free business loans up to ₹20 lakh (Shishu/Kishor/Tarun)",
      "बिना गारंटी ₹20 लाख तक का व्यवसाय ऋण (शिशु/किशोर/तरुण)",
      "biz", occ=["self_employed", "unemployed", "artisan", "street_vendor"],
      aMin=18, aMax=65),
    S("Stand-Up India", "स्टैंड-अप इंडिया",
      "₹10 lakh–₹1 crore loan for SC/ST and women first-time entrepreneurs",
      "एससी/एसटी व महिला उद्यमियों को ₹10 लाख–₹1 करोड़ तक ऋण",
      "biz", sow=True, aMin=18),
    S("PMEGP", "प्रधानमंत्री रोजगार सृजन कार्यक्रम",
      "15–35% margin-money subsidy on loans for new micro-enterprises",
      "नए सूक्ष्म उद्यमों के ऋण पर 15–35% मार्जिन मनी अनुदान",
      "biz", occ=["self_employed", "unemployed", "artisan"], aMin=18),
    S("PM Vishwakarma", "पीएम विश्वकर्मा योजना",
      "₹15,000 toolkit grant + loans up to ₹3 lakh at 5% for artisans",
      "कारीगरों को ₹15,000 टूलकिट अनुदान व 5% ब्याज पर ₹3 लाख तक ऋण",
      "biz", occ=["artisan"], aMin=18),
    S("PM SVANidhi", "पीएम स्वनिधि योजना",
      "Working-capital loans of ₹10,000–₹50,000 for street vendors",
      "रेहड़ी-पटरी विक्रेताओं को ₹10,000–₹50,000 कार्यशील पूंजी ऋण",
      "biz", occ=["street_vendor"], aMin=18),
    S("Startup India Seed Fund", "स्टार्टअप इंडिया सीड फंड",
      "Seed funding up to ₹50 lakh for recognised startups",
      "मान्यता प्राप्त स्टार्टअप को ₹50 लाख तक सीड फंडिंग",
      "biz", occ=["self_employed"], aMin=18),
    S("NHFDC Concessional Loans", "राष्ट्रीय दिव्यांगजन वित्त विकास निगम ऋण",
      "Concessional loans for entrepreneurs with disabilities",
      "दिव्यांग उद्यमियों हेतु रियायती दर पर ऋण",
      "biz", dis=True, aMin=18, aMax=60),

    # ---- Workers & unorganised sector ----
    S("e-Shram Card", "ई-श्रम कार्ड",
      "₹2 lakh accident insurance and welfare access for unorganised workers",
      "असंगठित श्रमिकों को ₹2 लाख दुर्घटना बीमा व कल्याण योजनाओं तक पहुंच",
      "worker", occ=["worker", "street_vendor", "artisan", "fisher", "homemaker"],
      aMin=16, aMax=59),
    S("PM Shram Yogi Maandhan", "प्रधानमंत्री श्रम योगी मानधन",
      "₹3,000 monthly pension after 60 for unorganised workers",
      "असंगठित श्रमिकों को 60 वर्ष के बाद ₹3,000 मासिक पेंशन",
      "pension", occ=["worker", "street_vendor", "artisan", "homemaker"],
      aMin=18, aMax=40, inc=216000),
    S("National Pension Scheme for Traders", "व्यापारियों हेतु राष्ट्रीय पेंशन योजना",
      "₹3,000 monthly pension after 60 for small traders and shopkeepers",
      "छोटे व्यापारियों व दुकानदारों को 60 के बाद ₹3,000 मासिक पेंशन",
      "pension", occ=["self_employed"], aMin=18, aMax=40),
    S("NAMASTE Scheme", "नमस्ते योजना",
      "Safety training, PPE kits and capital subsidy for sanitation workers",
      "सफाई कर्मियों को सुरक्षा प्रशिक्षण, पीपीई किट व पूंजी अनुदान",
      "worker", occ=["worker"], aMin=18),

    # ---- Education & scholarships ----
    S("National Means-cum-Merit Scholarship", "राष्ट्रीय साधन-सह-मेधा छात्रवृत्ति",
      "₹12,000 per year scholarship for classes 9–12",
      "कक्षा 9–12 के छात्रों को ₹12,000 वार्षिक छात्रवृत्ति",
      "edu", occ=["student"], aMin=12, aMax=18, inc=350000),
    S("Central Sector Scholarship (CSSS)", "केंद्रीय क्षेत्र छात्रवृत्ति (कॉलेज)",
      "₹12,000–₹20,000 per year for meritorious college students",
      "मेधावी कॉलेज छात्रों को ₹12,000–₹20,000 वार्षिक",
      "edu", occ=["student"], aMin=17, aMax=25, inc=450000),
    S("Central Sector Interest Subsidy (Education Loan)", "शिक्षा ऋण ब्याज सब्सिडी योजना",
      "Full interest subsidy on education loans during study period",
      "अध्ययन अवधि में शिक्षा ऋण पर पूर्ण ब्याज छूट",
      "edu", occ=["student"], aMin=16, aMax=35, inc=450000),
    S("PM Vidyalaxmi", "पीएम विद्यालक्ष्मी योजना",
      "Collateral-free education loans with interest subvention",
      "बिना गारंटी शिक्षा ऋण व ब्याज सहायता",
      "edu", occ=["student"], aMin=16, aMax=35, inc=800000),
    S("AICTE Pragati Scholarship", "एआईसीटीई प्रगति छात्रवृत्ति",
      "₹50,000 per year for girl students in technical education",
      "तकनीकी शिक्षा में छात्राओं को ₹50,000 वार्षिक",
      "edu", g="F", occ=["student"], aMin=16, aMax=30, inc=800000),
    S("AICTE Saksham Scholarship", "एआईसीटीई सक्षम छात्रवृत्ति",
      "₹50,000 per year for differently-abled students in technical courses",
      "तकनीकी पाठ्यक्रमों में दिव्यांग छात्रों को ₹50,000 वार्षिक",
      "edu", dis=True, occ=["student"], aMin=16, aMax=35, inc=800000),
    S("PM YASASVI Scholarship", "पीएम यशस्वी छात्रवृत्ति",
      "Top-class school scholarships for OBC/EBC/DNT students",
      "ओबीसी/ईबीसी/डीएनटी छात्रों को उत्कृष्ट विद्यालय छात्रवृत्ति",
      "edu", occ=["student"], cat=["obc"], aMin=10, aMax=18, inc=250000),
    S("National Fellowship for SC Students", "अनुसूचित जाति राष्ट्रीय फेलोशिप",
      "Fellowship for SC students pursuing MPhil/PhD",
      "एमफिल/पीएचडी कर रहे एससी छात्रों को फेलोशिप",
      "edu", occ=["student"], cat=["sc"], aMin=21, aMax=40),
    S("National Fellowship for ST Students", "अनुसूचित जनजाति राष्ट्रीय फेलोशिप",
      "Fellowship for ST students pursuing MPhil/PhD",
      "एमफिल/पीएचडी कर रहे एसटी छात्रों को फेलोशिप",
      "edu", occ=["student"], cat=["st"], aMin=21, aMax=40),
    S("National Overseas Scholarship", "राष्ट्रीय विदेश छात्रवृत्ति",
      "Financial support for SC/ST students to study abroad",
      "एससी/एसटी छात्रों को विदेश में उच्च शिक्षा हेतु सहायता",
      "edu", occ=["student"], cat=["sc", "st"], aMin=18, aMax=35, inc=800000),
    S("Ishan Uday Scholarship", "ईशान उदय छात्रवृत्ति",
      "₹5,400–₹7,800 monthly scholarship for North-East students",
      "पूर्वोत्तर के छात्रों को ₹5,400–₹7,800 मासिक छात्रवृत्ति",
      "edu", occ=["student"], aMin=17, aMax=25, inc=450000, sts=NE_STATES),
    S("Begum Hazrat Mahal Scholarship", "बेगम हज़रत महल राष्ट्रीय छात्रवृत्ति",
      "Scholarship for minority girl students of classes 9–12",
      "कक्षा 9–12 की अल्पसंख्यक छात्राओं को छात्रवृत्ति",
      "edu", g="F", occ=["student"], cat=["minority"], aMin=13, aMax=19, inc=200000),
    S("Free Coaching Scheme for SC/OBC", "एससी/ओबीसी निःशुल्क कोचिंग योजना",
      "Free coaching with stipend for competitive exams",
      "प्रतियोगी परीक्षाओं हेतु वजीफे सहित निःशुल्क कोचिंग",
      "edu", occ=["student", "unemployed"], cat=["sc", "obc"], aMin=18, aMax=30,
      inc=800000),
    S("Eklavya Model Residential Schools", "एकलव्य आदर्श आवासीय विद्यालय",
      "Free quality residential schooling for ST students (class 6–12)",
      "एसटी छात्रों को निःशुल्क गुणवत्तापूर्ण आवासीय शिक्षा (कक्षा 6–12)",
      "edu", occ=["student"], cat=["st"], aMin=10, aMax=18),
    S("Pre-Matric Scholarship for Students with Disabilities",
      "दिव्यांग छात्रों हेतु प्री-मैट्रिक छात्रवृत्ति",
      "Scholarship for students with disabilities in classes 9–10",
      "कक्षा 9–10 के दिव्यांग छात्रों को छात्रवृत्ति",
      "edu", dis=True, occ=["student"], aMin=12, aMax=18, inc=250000),
    S("Post-Matric Scholarship for Students with Disabilities",
      "दिव्यांग छात्रों हेतु पोस्ट-मैट्रिक छात्रवृत्ति",
      "Scholarship for students with disabilities in classes 11 and above",
      "कक्षा 11 व उससे ऊपर के दिव्यांग छात्रों को छात्रवृत्ति",
      "edu", dis=True, occ=["student"], aMin=16, aMax=30, inc=250000),
    S("UGC Single Girl Child Scholarship", "यूजीसी एकल बालिका छात्रवृत्ति",
      "₹36,200 per year for a single girl child pursuing postgraduate study",
      "स्नातकोत्तर कर रही एकल बालिका को ₹36,200 वार्षिक",
      "edu", g="F", occ=["student"], aMin=19, aMax=30),
    S("INSPIRE Scholarship", "इंस्पायर छात्रवृत्ति",
      "₹80,000 per year for top students pursuing basic sciences",
      "आधारभूत विज्ञान के शीर्ष छात्रों को ₹80,000 वार्षिक",
      "edu", occ=["student"], aMin=17, aMax=22),
    S("PM Research Fellowship", "प्रधानमंत्री अनुसंधान फेलोशिप",
      "Up to ₹80,000 monthly fellowship for PhD research at top institutes",
      "शीर्ष संस्थानों में पीएचडी शोध हेतु ₹80,000 तक मासिक फेलोशिप",
      "edu", occ=["student"], aMin=21, aMax=35),
    S("Khelo India Scholarship", "खेलो इंडिया छात्रवृत्ति",
      "₹6.28 lakh annual support for talented young athletes",
      "प्रतिभाशाली युवा खिलाड़ियों को ₹6.28 लाख वार्षिक सहायता",
      "edu", aMin=8, aMax=25),
    S("Beti Bachao Beti Padhao", "बेटी बचाओ बेटी पढ़ाओ",
      "Support and incentives for girl-child education and welfare",
      "बालिका शिक्षा व कल्याण हेतु सहायता और प्रोत्साहन",
      "wcd", g="F", aMax=18),

    # ---- Skills & employment ----
    S("PM Kaushal Vikas Yojana 4.0", "प्रधानमंत्री कौशल विकास योजना 4.0",
      "Free industry-relevant skill training with certification",
      "प्रमाणपत्र सहित निःशुल्क उद्योग-प्रासंगिक कौशल प्रशिक्षण",
      "skill", occ=["student", "unemployed", "worker"], aMin=15, aMax=45),
    S("DDU-GKY", "दीन दयाल उपाध्याय ग्रामीण कौशल्य योजना",
      "Free residential skill training with placement for rural youth",
      "ग्रामीण युवाओं को प्लेसमेंट सहित निःशुल्क आवासीय कौशल प्रशिक्षण",
      "skill", occ=["unemployed", "student", "worker"], aMin=15, aMax=35,
      res="R", inc=250000),
    S("Rail Kaushal Vikas Yojana", "रेल कौशल विकास योजना",
      "Free technical skill training by Indian Railways",
      "भारतीय रेलवे द्वारा निःशुल्क तकनीकी कौशल प्रशिक्षण",
      "skill", occ=["unemployed", "student"], aMin=18, aMax=35),
    S("National Apprenticeship Promotion Scheme", "राष्ट्रीय शिक्षुता प्रोत्साहन योजना",
      "Government-shared stipend during industry apprenticeship",
      "उद्योग अप्रेंटिसशिप के दौरान सरकार द्वारा साझा वजीफा",
      "skill", occ=["student", "unemployed"], aMin=16, aMax=35),
    S("PM Internship Scheme", "पीएम इंटर्नशिप योजना",
      "₹5,000 monthly internship stipend in India's top 500 companies",
      "शीर्ष 500 कंपनियों में ₹5,000 मासिक वजीफे के साथ इंटर्नशिप",
      "skill", occ=["unemployed", "student"], aMin=21, aMax=24, inc=800000),
    S("Agnipath Scheme", "अग्निपथ योजना",
      "4-year service in armed forces with ₹11.7 lakh Seva Nidhi package",
      "सशस्त्र बलों में 4 वर्ष की सेवा व ₹11.7 लाख सेवा निधि",
      "skill", occ=["student", "unemployed"], aMin=17, aMax=23),
    S("PM-DAKSH", "पीएम-दक्ष योजना",
      "Free skill development for SC, OBC and sanitation workers",
      "एससी, ओबीसी व सफाई कर्मियों को निःशुल्क कौशल विकास",
      "skill", cat=["sc", "obc"], aMin=18, aMax=45, inc=300000),
    S("Seekho aur Kamao", "सीखो और कमाओ",
      "Skill training with placement support for minority youth",
      "अल्पसंख्यक युवाओं को प्लेसमेंट सहायता सहित कौशल प्रशिक्षण",
      "skill", cat=["minority"], aMin=14, aMax=35),

    # ---- Women, children & social welfare ----
    S("Nai Roshni", "नई रोशनी योजना",
      "Leadership development training for minority women",
      "अल्पसंख्यक महिलाओं हेतु नेतृत्व विकास प्रशिक्षण",
      "wcd", g="F", cat=["minority"], aMin=18, aMax=65),
    S("Palna (National Creche Scheme)", "पालना (राष्ट्रीय शिशुगृह योजना)",
      "Subsidised day-care creche services for children of working mothers",
      "कामकाजी माताओं के बच्चों हेतु रियायती डे-केयर शिशुगृह",
      "wcd", g="F", occ=["salaried", "worker", "self_employed"], aMin=18, aMax=50),
    S("Sakhi Niwas (Working Women Hostel)", "सखी निवास (कामकाजी महिला छात्रावास)",
      "Safe and affordable hostel accommodation for working women",
      "कामकाजी महिलाओं हेतु सुरक्षित व किफायती छात्रावास",
      "wcd", g="F", occ=["salaried", "worker", "self_employed"], aMin=18, aMax=60),
    S("Mission Vatsalya Sponsorship", "मिशन वात्सल्य प्रायोजन",
      "₹4,000 monthly support for orphaned and vulnerable children",
      "अनाथ व असहाय बच्चों को ₹4,000 मासिक सहायता",
      "wcd", aMax=18, inc=216000),
    S("SMILE Scheme", "स्माइल योजना",
      "Shelter, skill and welfare support for transgender persons",
      "ट्रांसजेंडर व्यक्तियों हेतु आश्रय, कौशल व कल्याण सहायता",
      "social", g="O", aMin=18),
]

# --------------------------------------------------------------------------
# 2. Curated flagship State schemes  (state → list)
# --------------------------------------------------------------------------
STATE_SCHEMES = {
    "Jharkhand": [
        S("Mukhyamantri Maiya Samman Yojana", "मुख्यमंत्री मंईयां सम्मान योजना",
          "₹2,500 monthly financial assistance to women aged 18–50",
          "18–50 वर्ष की महिलाओं को ₹2,500 मासिक आर्थिक सहायता",
          "wcd", "S", "Jharkhand", g="F", aMin=18, aMax=50, inc=800000),
        S("Abua Awas Yojana", "अबुआ आवास योजना",
          "3-room pucca house (₹2 lakh) for families without a pucca home",
          "पक्का मकान विहीन परिवारों को 3 कमरों का पक्का घर (₹2 लाख)",
          "housing", "S", "Jharkhand", inc=300000, res="R"),
        S("Guruji Student Credit Card", "गुरुजी स्टूडेंट क्रेडिट कार्ड योजना",
          "Education loans up to ₹15 lakh at 4% for higher studies",
          "उच्च शिक्षा हेतु 4% ब्याज पर ₹15 लाख तक शिक्षा ऋण",
          "edu", "S", "Jharkhand", occ=["student"], aMin=16, aMax=40),
        S("Savitribai Phule Kishori Samriddhi Yojana",
          "सावित्रीबाई फुले किशोरी समृद्धि योजना",
          "₹40,000 total assistance to girl students from class 8 to age 18",
          "कक्षा 8 से 18 वर्ष तक छात्राओं को कुल ₹40,000 की सहायता",
          "edu", "S", "Jharkhand", g="F", occ=["student"], aMin=11, aMax=20,
          inc=300000),
        S("Mukhyamantri Sarvajan Pension Yojana", "मुख्यमंत्री सर्वजन पेंशन योजना",
          "₹1,000 universal monthly pension for elderly, widows and disabled",
          "वृद्धों, विधवाओं व दिव्यांगों को ₹1,000 सार्वभौमिक मासिक पेंशन",
          "pension", "S", "Jharkhand", aMin=50),
        S("Birsa Harit Gram Yojana", "बिरसा हरित ग्राम योजना",
          "Fruit-tree plantation on private land with 100% support + wages",
          "निजी भूमि पर फलदार वृक्षारोपण हेतु शत-प्रतिशत सहायता व मजदूरी",
          "agri", "S", "Jharkhand", occ=["farmer"], res="R", aMin=18),
        S("Mukhyamantri Pashudhan Vikas Yojana", "मुख्यमंत्री पशुधन विकास योजना",
          "Up to 90% subsidy on cows, goats, pigs and poultry units",
          "गाय, बकरी, सूअर व मुर्गी पालन इकाइयों पर 90% तक अनुदान",
          "agri", "S", "Jharkhand", occ=["farmer"], res="R", aMin=18),
        S("Sona Sobran Dhoti-Saree Yojana", "सोना सोबरन धोती-साड़ी योजना",
          "Dhoti/lungi and saree at ₹10 each, twice a year for ration families",
          "राशन कार्ड परिवारों को ₹10 में धोती/लुंगी व साड़ी, वर्ष में दो बार",
          "social", "S", "Jharkhand", inc=250000),
        S("Mukhyamantri Rojgar Srijan Yojana", "मुख्यमंत्री रोजगार सृजन योजना",
          "Loans up to ₹25 lakh with 40% subsidy for self-employment",
          "स्वरोजगार हेतु 40% अनुदान सहित ₹25 लाख तक ऋण",
          "biz", "S", "Jharkhand", cat=["sc", "st", "obc", "minority"],
          occ=["self_employed", "unemployed"], aMin=18, aMax=45, inc=500000),
        S("Jharkhand Krishi Rin Mafi Yojana", "झारखंड कृषि ऋण माफी योजना",
          "Farm loan waiver up to ₹2 lakh for farmers",
          "किसानों का ₹2 लाख तक का कृषि ऋण माफ",
          "agri", "S", "Jharkhand", occ=["farmer"], aMin=18),
        S("Mukhyamantri Sukhad Rahat Yojana", "मुख्यमंत्री सुखाड़ राहत योजना",
          "₹3,500 relief per drought-affected farmer family",
          "सूखा प्रभावित किसान परिवारों को ₹3,500 राहत",
          "agri", "S", "Jharkhand", occ=["farmer"], res="R"),
        S("Eklavya Prashikshan Yojana", "एकलव्य प्रशिक्षण योजना",
          "Free coaching for UPSC/JPSC/banking exams with stipend",
          "यूपीएससी/जेपीएससी/बैंकिंग परीक्षाओं की निःशुल्क कोचिंग व वजीफा",
          "edu", "S", "Jharkhand", occ=["student", "unemployed"], aMin=18,
          aMax=35, inc=500000),
        S("Manki Munda Scholarship", "मानकी मुंडा छात्रवृत्ति योजना",
          "Scholarship for tribal girl students in engineering/diploma",
          "इंजीनियरिंग/डिप्लोमा में आदिवासी छात्राओं को छात्रवृत्ति",
          "edu", "S", "Jharkhand", g="F", occ=["student"], cat=["st"],
          aMin=16, aMax=30),
        S("Jharkhand Petrol Subsidy Yojana", "झारखंड पेट्रोल सब्सिडी योजना",
          "₹25 per litre petrol subsidy (10 L/month) for ration-card two-wheeler owners",
          "राशन कार्ड धारक दोपहिया मालिकों को ₹25 प्रति लीटर पेट्रोल सब्सिडी",
          "social", "S", "Jharkhand", inc=250000, aMin=18),
        S("Phulo Jhano Ashirwad Abhiyan", "फूलो झानो आशीर्वाद अभियान",
          "Interest-free loans + livelihood support for women leaving haria-daru trade",
          "हड़िया-दारू व्यवसाय छोड़ने वाली महिलाओं को ब्याज-मुक्त ऋण व आजीविका सहायता",
          "wcd", "S", "Jharkhand", g="F", aMin=18, aMax=60),
        S("Mukhyamantri Gram Gadi Yojana", "मुख्यमंत्री ग्राम गाड़ी योजना",
          "Free/concessional rural bus travel for seniors, students and disabled",
          "वृद्धों, छात्रों व दिव्यांगों को ग्रामीण बस यात्रा निःशुल्क/रियायती",
          "social", "S", "Jharkhand", res="R"),
    ],
    "Uttar Pradesh": [
        S("Mukhyamantri Kanya Sumangala Yojana", "मुख्यमंत्री कन्या सुमंगला योजना",
          "₹25,000 staged assistance for a girl child from birth to graduation",
          "बेटी को जन्म से स्नातक तक ₹25,000 की चरणबद्ध सहायता",
          "wcd", "S", "Uttar Pradesh", g="F", aMax=23, inc=300000),
        S("UP Vridhavastha Pension", "उत्तर प्रदेश वृद्धावस्था पेंशन",
          "₹1,000 monthly pension for poor senior citizens",
          "गरीब वरिष्ठ नागरिकों को ₹1,000 मासिक पेंशन",
          "pension", "S", "Uttar Pradesh", aMin=60, inc=56460),
        S("Mukhyamantri Abhyudaya Yojana", "मुख्यमंत्री अभ्युदय योजना",
          "Free coaching for UPSC/UPPSC/NEET/JEE aspirants",
          "यूपीएससी/यूपीपीएससी/नीट/जेईई की निःशुल्क कोचिंग",
          "edu", "S", "Uttar Pradesh", occ=["student", "unemployed"], aMin=16,
          aMax=35),
        S("Mukhyamantri Yuva Udyami Vikas Abhiyan", "मुख्यमंत्री युवा उद्यमी विकास अभियान",
          "Interest-free loans up to ₹5 lakh for young entrepreneurs",
          "युवा उद्यमियों को ₹5 लाख तक ब्याज-मुक्त ऋण",
          "biz", "S", "Uttar Pradesh", occ=["self_employed", "unemployed"],
          aMin=21, aMax=40),
    ],
    "Bihar": [
        S("Mukhyamantri Kanya Utthan Yojana", "मुख्यमंत्री कन्या उत्थान योजना",
          "Up to ₹94,100 staged support for girls from birth to graduation",
          "बेटियों को जन्म से स्नातक तक ₹94,100 तक की सहायता",
          "wcd", "S", "Bihar", g="F", aMax=25),
        S("Bihar Student Credit Card", "बिहार स्टूडेंट क्रेडिट कार्ड योजना",
          "Education loans up to ₹4 lakh at simple interest for higher studies",
          "उच्च शिक्षा हेतु ₹4 लाख तक शिक्षा ऋण",
          "edu", "S", "Bihar", occ=["student"], aMin=17, aMax=25),
        S("Mukhyamantri Nishchay Swayam Sahayata Bhatta",
          "मुख्यमंत्री निश्चय स्वयं सहायता भत्ता",
          "₹1,000 monthly allowance for unemployed youth (20–25)",
          "बेरोजगार युवाओं (20–25) को ₹1,000 मासिक भत्ता",
          "skill", "S", "Bihar", occ=["unemployed"], aMin=20, aMax=25),
        S("Mukhyamantri Balika Cycle Yojana", "मुख्यमंत्री बालिका साइकिल योजना",
          "₹3,000 for bicycles to girl students of class 9",
          "कक्षा 9 की छात्राओं को साइकिल हेतु ₹3,000",
          "edu", "S", "Bihar", g="F", occ=["student"], aMin=12, aMax=18),
    ],
    "Madhya Pradesh": [
        S("Ladli Behna Yojana", "लाडली बहना योजना",
          "₹1,250 monthly assistance to women aged 21–60",
          "21–60 वर्ष की महिलाओं को ₹1,250 मासिक सहायता",
          "wcd", "S", "Madhya Pradesh", g="F", aMin=21, aMax=60, inc=250000),
        S("Ladli Laxmi Yojana", "लाडली लक्ष्मी योजना",
          "₹1 lakh+ assurance for girl child education and marriage",
          "बेटी की शिक्षा व विवाह हेतु ₹1 लाख+ का आश्वासन",
          "wcd", "S", "Madhya Pradesh", g="F", aMax=21),
        S("Mukhyamantri Kanya Vivah Yojana", "मुख्यमंत्री कन्या विवाह योजना",
          "₹55,000 marriage assistance for daughters of poor families",
          "गरीब परिवारों की बेटियों के विवाह हेतु ₹55,000 सहायता",
          "social", "S", "Madhya Pradesh", g="F", aMin=18, inc=200000),
        S("Mukhyamantri Medhavi Vidyarthi Yojana", "मुख्यमंत्री मेधावी विद्यार्थी योजना",
          "Full fee payment for meritorious students in higher education",
          "मेधावी छात्रों की उच्च शिक्षा की पूरी फीस सरकार द्वारा",
          "edu", "S", "Madhya Pradesh", occ=["student"], aMin=17, aMax=25,
          inc=600000),
    ],
    "Maharashtra": [
        S("Mukhyamantri Majhi Ladki Bahin Yojana", "मुख्यमंत्री माझी लाडकी बहीण योजना",
          "₹1,500 monthly assistance to women aged 21–65",
          "21–65 वर्ष की महिलाओं को ₹1,500 मासिक सहायता",
          "wcd", "S", "Maharashtra", g="F", aMin=21, aMax=65, inc=250000),
        S("Shravan Bal Seva Rajya Nivruttivetan", "श्रावण बाल सेवा राज्य निवृत्तिवेतन",
          "₹1,500 monthly pension for senior citizens",
          "वरिष्ठ नागरिकों को ₹1,500 मासिक पेंशन",
          "pension", "S", "Maharashtra", aMin=65, inc=210000),
        S("Mahatma Jyotirao Phule Jan Arogya Yojana",
          "महात्मा ज्योतिराव फुले जन आरोग्य योजना",
          "Free hospital treatment up to ₹5 lakh per family",
          "प्रति परिवार ₹5 लाख तक निःशुल्क अस्पताल इलाज",
          "health", "S", "Maharashtra", inc=500000),
        S("Lek Ladki Yojana", "लेक लाडकी योजना",
          "₹1.01 lakh staged assistance for girls of yellow/orange ration families",
          "पीले/नारंगी राशन कार्ड परिवारों की बेटियों को ₹1.01 लाख चरणबद्ध सहायता",
          "wcd", "S", "Maharashtra", g="F", aMax=18, inc=100000),
    ],
    "Rajasthan": [
        S("Mukhyamantri Ayushman Arogya Yojana", "मुख्यमंत्री आयुष्मान आरोग्य योजना",
          "Health cover up to ₹25 lakh per family per year",
          "प्रति परिवार प्रति वर्ष ₹25 लाख तक स्वास्थ्य कवर",
          "health", "S", "Rajasthan"),
        S("Palanhar Yojana", "पालनहार योजना",
          "₹750–₹2,500 monthly for care of orphaned/vulnerable children",
          "अनाथ/असहाय बच्चों की देखभाल हेतु ₹750–₹2,500 मासिक",
          "wcd", "S", "Rajasthan", aMax=18),
        S("Mukhyamantri Kisan Samman Nidhi (Top-up)", "मुख्यमंत्री किसान सम्मान निधि",
          "₹2,000 additional annual support over PM-KISAN for farmers",
          "पीएम-किसान के अतिरिक्त किसानों को ₹2,000 वार्षिक सहायता",
          "agri", "S", "Rajasthan", occ=["farmer"], aMin=18),
        S("Lado Protsahan Yojana", "लाडो प्रोत्साहन योजना",
          "₹1 lakh+ savings bond staged support for girl child",
          "बेटी के जन्म पर ₹1 लाख+ का चरणबद्ध बचत बांड",
          "wcd", "S", "Rajasthan", g="F", aMax=21),
    ],
    "West Bengal": [
        S("Lakshmir Bhandar", "लक्ष्मी भंडार",
          "₹1,000–₹1,200 monthly income support for women (25–60)",
          "महिलाओं (25–60) को ₹1,000–₹1,200 मासिक आय सहायता",
          "wcd", "S", "West Bengal", g="F", aMin=25, aMax=60),
        S("Kanyashree Prakalpa", "कन्याश्री प्रकल्प",
          "₹1,000/year + ₹25,000 one-time grant for girl students (13–19)",
          "छात्राओं (13–19) को ₹1,000 वार्षिक व ₹25,000 एकमुश्त अनुदान",
          "edu", "S", "West Bengal", g="F", occ=["student"], aMin=13, aMax=19),
        S("Rupashree Prakalpa", "रूपश्री प्रकल्प",
          "₹25,000 one-time marriage assistance for poor families' daughters",
          "गरीब परिवारों की बेटियों को विवाह हेतु ₹25,000 एकमुश्त सहायता",
          "social", "S", "West Bengal", g="F", aMin=18, inc=150000),
        S("Krishak Bandhu", "कृषक बंधु",
          "₹10,000 per year assistance + ₹2 lakh death benefit for farmers",
          "किसानों को ₹10,000 वार्षिक सहायता व ₹2 लाख मृत्यु लाभ",
          "agri", "S", "West Bengal", occ=["farmer"], aMin=18, aMax=60),
        S("Swasthya Sathi", "स्वास्थ्य साथी",
          "₹5 lakh cashless health cover per family",
          "प्रति परिवार ₹5 लाख कैशलेस स्वास्थ्य कवर",
          "health", "S", "West Bengal"),
        S("Yuvashree", "युवाश्री",
          "₹1,500 monthly allowance for enlisted unemployed youth",
          "पंजीकृत बेरोजगार युवाओं को ₹1,500 मासिक भत्ता",
          "skill", "S", "West Bengal", occ=["unemployed"], aMin=18, aMax=45),
    ],
    "Tamil Nadu": [
        S("Kalaignar Magalir Urimai Thogai", "कलैग्नर मगलिर उरिमई थोगई",
          "₹1,000 monthly rights assistance for eligible women heads of family",
          "पात्र परिवार-प्रमुख महिलाओं को ₹1,000 मासिक सहायता",
          "wcd", "S", "Tamil Nadu", g="F", aMin=21, inc=250000),
        S("Pudhumai Penn Scheme", "पुधुमई पेन योजना",
          "₹1,000 monthly for girls from govt schools pursuing higher education",
          "सरकारी स्कूल से उच्च शिक्षा में जाने वाली छात्राओं को ₹1,000 मासिक",
          "edu", "S", "Tamil Nadu", g="F", occ=["student"], aMin=17, aMax=25),
        S("Chief Minister's Comprehensive Health Insurance",
          "मुख्यमंत्री व्यापक स्वास्थ्य बीमा योजना",
          "₹5 lakh annual family health cover",
          "₹5 लाख वार्षिक पारिवारिक स्वास्थ्य कवर",
          "health", "S", "Tamil Nadu", inc=120000),
        S("Moovalur Ramamirtham Scheme", "मूवलुर रामामिर्थम योजना",
          "Higher-education incentive for girls to prevent early marriage",
          "बाल विवाह रोकथाम हेतु छात्राओं को उच्च शिक्षा प्रोत्साहन",
          "edu", "S", "Tamil Nadu", g="F", occ=["student"], aMin=17, aMax=25),
    ],
    "Karnataka": [
        S("Gruha Lakshmi", "गृह लक्ष्मी योजना",
          "₹2,000 monthly assistance to women heads of household",
          "परिवार की महिला मुखिया को ₹2,000 मासिक सहायता",
          "wcd", "S", "Karnataka", g="F", aMin=18),
        S("Gruha Jyothi", "गृह ज्योति योजना",
          "Free electricity up to 200 units per month",
          "प्रति माह 200 यूनिट तक मुफ्त बिजली",
          "social", "S", "Karnataka"),
        S("Anna Bhagya", "अन्न भाग्य योजना",
          "10 kg free rice per person per month for priority families",
          "प्राथमिकता परिवारों को प्रति व्यक्ति 10 किलो मुफ्त चावल",
          "food", "S", "Karnataka", inc=250000),
        S("Yuva Nidhi", "युवा निधि योजना",
          "₹3,000/month for unemployed graduates, ₹1,500 for diploma holders",
          "बेरोजगार स्नातकों को ₹3,000 व डिप्लोमा धारकों को ₹1,500 मासिक",
          "skill", "S", "Karnataka", occ=["unemployed"], aMin=18, aMax=35),
        S("Shakti Scheme", "शक्ति योजना",
          "Free bus travel for women in non-premium state buses",
          "राज्य की साधारण बसों में महिलाओं को मुफ्त यात्रा",
          "social", "S", "Karnataka", g="F"),
    ],
    "Telangana": [
        S("Rythu Bharosa", "रैतु भरोसा",
          "₹12,000 per acre per year investment support for farmers",
          "किसानों को ₹12,000 प्रति एकड़ प्रति वर्ष निवेश सहायता",
          "agri", "S", "Telangana", occ=["farmer"], aMin=18),
        S("Kalyana Lakshmi / Shaadi Mubarak", "कल्याण लक्ष्मी / शादी मुबारक",
          "₹1,00,116 marriage assistance for poor families' daughters",
          "गरीब परिवारों की बेटियों के विवाह हेतु ₹1,00,116 सहायता",
          "social", "S", "Telangana", g="F", aMin=18, inc=200000),
        S("Aasara Pension", "आसरा पेंशन",
          "₹2,016 monthly pension for elderly, widows and disabled",
          "वृद्धों, विधवाओं व दिव्यांगों को ₹2,016 मासिक पेंशन",
          "pension", "S", "Telangana", aMin=57, inc=200000),
        S("Mahalakshmi Scheme", "महालक्ष्मी योजना",
          "₹2,500 monthly for women + free bus travel + ₹500 LPG cylinder",
          "महिलाओं को ₹2,500 मासिक, मुफ्त बस यात्रा व ₹500 में सिलेंडर",
          "wcd", "S", "Telangana", g="F", aMin=18, inc=250000),
    ],
    "Andhra Pradesh": [
        S("NTR Bharosa Pension", "एनटीआर भरोसा पेंशन",
          "₹4,000 monthly pension for elderly, widows and disabled",
          "वृद्धों, विधवाओं व दिव्यांगों को ₹4,000 मासिक पेंशन",
          "pension", "S", "Andhra Pradesh", aMin=60, inc=120000),
        S("Thalliki Vandanam", "तल्लीकी वंदनम",
          "₹15,000 per school-going child per year to mothers",
          "स्कूल जाने वाले प्रत्येक बच्चे पर माताओं को ₹15,000 वार्षिक",
          "edu", "S", "Andhra Pradesh", inc=270000),
        S("Deepam Scheme", "दीपम योजना",
          "3 free LPG cylinders per year for eligible women",
          "पात्र महिलाओं को वर्ष में 3 मुफ्त एलपीजी सिलेंडर",
          "social", "S", "Andhra Pradesh", g="F", aMin=18, inc=270000),
        S("Annadata Sukhibhava", "अन्नदाता सुखीभव",
          "₹20,000 annual support to farmer families (incl. PM-KISAN)",
          "किसान परिवारों को ₹20,000 वार्षिक सहायता (पीएम-किसान सहित)",
          "agri", "S", "Andhra Pradesh", occ=["farmer"], aMin=18),
    ],
    "Gujarat": [
        S("Namo Lakshmi Yojana", "नमो लक्ष्मी योजना",
          "₹50,000 total scholarship for girl students of classes 9–12",
          "कक्षा 9–12 की छात्राओं को कुल ₹50,000 छात्रवृत्ति",
          "edu", "S", "Gujarat", g="F", occ=["student"], aMin=13, aMax=20,
          inc=600000),
        S("Namo Shri Yojana", "नमो श्री योजना",
          "₹12,000 maternity assistance for eligible mothers",
          "पात्र माताओं को ₹12,000 मातृत्व सहायता",
          "wcd", "S", "Gujarat", g="F", preg=True, aMin=18, inc=600000),
        S("Mukhyamantri Yuva Swavalamban Yojana", "मुख्यमंत्री युवा स्वावलंबन योजना",
          "Up to ₹2 lakh higher-education assistance for meritorious students",
          "मेधावी छात्रों को उच्च शिक्षा हेतु ₹2 लाख तक सहायता",
          "edu", "S", "Gujarat", occ=["student"], aMin=17, aMax=25, inc=600000),
        S("Vahli Dikri Yojana", "वहाली डिकरी योजना",
          "₹1.1 lakh staged support for girl child till marriage/education",
          "बेटी को शिक्षा/विवाह तक ₹1.1 लाख चरणबद्ध सहायता",
          "wcd", "S", "Gujarat", g="F", aMax=18, inc=200000),
    ],
    "Kerala": [
        S("Karunya Arogya Suraksha Padhathi", "करुण्य आरोग्य सुरक्षा पद्धति",
          "₹5 lakh annual health cover for poor families",
          "गरीब परिवारों को ₹5 लाख वार्षिक स्वास्थ्य कवर",
          "health", "S", "Kerala", inc=300000),
        S("Kerala Social Security Pension", "केरल सामाजिक सुरक्षा पेंशन",
          "₹1,600 monthly welfare pension for elderly/widows/disabled",
          "वृद्धों/विधवाओं/दिव्यांगों को ₹1,600 मासिक कल्याण पेंशन",
          "pension", "S", "Kerala", aMin=60, inc=100000),
        S("Snehapoorvam Scheme", "स्नेहपूर्वम योजना",
          "Monthly financial support for orphaned children",
          "अनाथ बच्चों को मासिक आर्थिक सहायता",
          "wcd", "S", "Kerala", aMax=18),
        S("Vidyajyothi Scheme", "विद्याज्योति योजना",
          "Educational aid for uniforms and books to poor students",
          "गरीब छात्रों को वर्दी व पुस्तकों हेतु शैक्षिक सहायता",
          "edu", "S", "Kerala", occ=["student"], aMin=5, aMax=18, inc=100000),
    ],
    "Punjab": [
        S("Aashirwad Scheme", "आशीर्वाद योजना",
          "₹51,000 marriage assistance for daughters of poor SC/BC families",
          "गरीब एससी/बीसी परिवारों की बेटियों के विवाह हेतु ₹51,000",
          "social", "S", "Punjab", g="F", aMin=18, cat=["sc", "obc"],
          inc=200000),
        S("Free Bus Travel for Women", "महिलाओं हेतु मुफ्त बस यात्रा",
          "Free travel for women in Punjab government buses",
          "पंजाब सरकारी बसों में महिलाओं को मुफ्त यात्रा",
          "social", "S", "Punjab", g="F"),
        S("Punjab Old Age Pension", "पंजाब वृद्धावस्था पेंशन",
          "₹1,500 monthly pension for senior citizens",
          "वरिष्ठ नागरिकों को ₹1,500 मासिक पेंशन",
          "pension", "S", "Punjab", aMin=58, inc=100000),
    ],
    "Haryana": [
        S("Old Age Samman Allowance", "वृद्धावस्था सम्मान भत्ता",
          "₹3,000 monthly allowance for senior citizens",
          "वरिष्ठ नागरिकों को ₹3,000 मासिक भत्ता",
          "pension", "S", "Haryana", aMin=60, inc=300000),
        S("Ladli Social Security Allowance", "लाडली सामाजिक सुरक्षा भत्ता",
          "₹3,000 monthly for families with only daughters",
          "केवल बेटियों वाले परिवारों को ₹3,000 मासिक",
          "wcd", "S", "Haryana", aMin=45, inc=300000),
        S("Mukhyamantri Vivah Shagun Yojana", "मुख्यमंत्री विवाह शगुन योजना",
          "Up to ₹71,000 marriage assistance for poor families' daughters",
          "गरीब परिवारों की बेटियों के विवाह हेतु ₹71,000 तक",
          "social", "S", "Haryana", g="F", aMin=18, inc=180000),
    ],
    "Odisha": [
        S("Subhadra Yojana", "सुभद्रा योजना",
          "₹10,000 per year (₹50,000 over 5 years) to women aged 21–60",
          "21–60 वर्ष की महिलाओं को ₹10,000 वार्षिक (5 वर्षों में ₹50,000)",
          "wcd", "S", "Odisha", g="F", aMin=21, aMax=60, inc=250000),
        S("KALIA Yojana", "कालिया योजना",
          "₹10,000 per year cultivation support for small farmers",
          "छोटे किसानों को ₹10,000 वार्षिक कृषि सहायता",
          "agri", "S", "Odisha", occ=["farmer"], aMin=18),
        S("Madhu Babu Pension Yojana", "मधु बाबू पेंशन योजना",
          "₹500–₹900 monthly pension for elderly, widows and disabled",
          "वृद्धों, विधवाओं व दिव्यांगों को ₹500–₹900 मासिक पेंशन",
          "pension", "S", "Odisha", aMin=60, inc=100000),
        S("Gopabandhu Jan Arogya Yojana", "गोपबंधु जन आरोग्य योजना",
          "₹5 lakh health cover per family (₹10 lakh for women)",
          "प्रति परिवार ₹5 लाख (महिलाओं हेतु ₹10 लाख) स्वास्थ्य कवर",
          "health", "S", "Odisha", inc=300000),
    ],
    "Chhattisgarh": [
        S("Mahtari Vandan Yojana", "महतारी वंदन योजना",
          "₹1,000 monthly assistance to married women",
          "विवाहित महिलाओं को ₹1,000 मासिक सहायता",
          "wcd", "S", "Chhattisgarh", g="F", aMin=21, inc=250000),
        S("Krishak Unnati Yojana", "कृषक उन्नति योजना",
          "Input subsidy on paddy procurement for farmers",
          "धान खरीद पर किसानों को आदान सहायता",
          "agri", "S", "Chhattisgarh", occ=["farmer"], aMin=18),
        S("Noni Suraksha Yojana", "नोनी सुरक्षा योजना",
          "₹1 lakh assurance for girl child at age 18",
          "बेटी को 18 वर्ष की आयु पर ₹1 लाख का आश्वासन",
          "wcd", "S", "Chhattisgarh", g="F", aMax=18, bpl=True),
    ],
    "Assam": [
        S("Orunodoi Scheme", "अरुणोदय योजना",
          "₹1,250 monthly support to poor women-headed households",
          "गरीब महिला-प्रधान परिवारों को ₹1,250 मासिक सहायता",
          "wcd", "S", "Assam", g="F", aMin=18, inc=200000),
        S("Nijut Moina Scheme", "निजुत मोइना योजना",
          "₹1,000–₹2,500 monthly for girls in higher secondary to PG",
          "उच्चतर माध्यमिक से पीजी तक छात्राओं को ₹1,000–₹2,500 मासिक",
          "edu", "S", "Assam", g="F", occ=["student"], aMin=15, aMax=27),
    ],
    "Delhi": [
        S("Delhi Old Age Pension", "दिल्ली वृद्धावस्था पेंशन",
          "₹2,000–₹2,500 monthly pension for senior citizens",
          "वरिष्ठ नागरिकों को ₹2,000–₹2,500 मासिक पेंशन",
          "pension", "S", "Delhi", aMin=60, inc=100000),
        S("Delhi Ladli Yojana", "दिल्ली लाडली योजना",
          "Staged deposits up to ₹36,000 for girl child education",
          "बेटी की शिक्षा हेतु ₹36,000 तक चरणबद्ध जमा",
          "wcd", "S", "Delhi", g="F", aMax=18, inc=100000),
        S("Delhi Free Power Subsidy", "दिल्ली मुफ्त बिजली सब्सिडी",
          "Free electricity up to 200 units per month",
          "प्रति माह 200 यूनिट तक मुफ्त बिजली",
          "social", "S", "Delhi"),
        S("Delhi Free Bus Travel for Women", "महिलाओं हेतु मुफ्त बस यात्रा (दिल्ली)",
          "Free travel for women in DTC and cluster buses",
          "डीटीसी व क्लस्टर बसों में महिलाओं को मुफ्त यात्रा",
          "social", "S", "Delhi", g="F"),
    ],
    "Jammu and Kashmir": [
        S("Ladli Beti Scheme", "लाडली बेटी योजना",
          "₹1,000 monthly deposit from birth for girl child of poor families",
          "गरीब परिवारों की बेटी के जन्म से ₹1,000 मासिक जमा",
          "wcd", "S", "Jammu and Kashmir", g="F", aMax=14, inc=75000),
        S("Marriage Assistance Scheme (JK)", "विवाह सहायता योजना (जम्मू-कश्मीर)",
          "₹75,000 marriage assistance for daughters of poor families",
          "गरीब परिवारों की बेटियों के विवाह हेतु ₹75,000",
          "social", "S", "Jammu and Kashmir", g="F", aMin=18, inc=100000),
    ],
    "Himachal Pradesh": [
        S("Indira Gandhi Pyari Behna Yojana", "इंदिरा गांधी प्यारी बहना योजना",
          "₹1,500 monthly assistance to women aged 18–60",
          "18–60 वर्ष की महिलाओं को ₹1,500 मासिक सहायता",
          "wcd", "S", "Himachal Pradesh", g="F", aMin=18, aMax=60),
        S("Mukhyamantri Sukh-Ashray Yojana", "मुख्यमंत्री सुख-आश्रय योजना",
          "Education, pocket money and startup support for orphans",
          "अनाथ बच्चों को शिक्षा, जेब-खर्च व स्टार्टअप सहायता",
          "wcd", "S", "Himachal Pradesh", aMax=27),
    ],
    "Uttarakhand": [
        S("Nanda Gaura Yojana", "नंदा गौरा योजना",
          "₹62,000 staged assistance for girl child (birth + class 12)",
          "बेटी को जन्म व कक्षा 12 पर कुल ₹62,000 सहायता",
          "wcd", "S", "Uttarakhand", g="F", aMax=25, inc=72000),
        S("Uttarakhand Old Age Pension", "उत्तराखंड वृद्धावस्था पेंशन",
          "₹1,500 monthly pension for senior citizens",
          "वरिष्ठ नागरिकों को ₹1,500 मासिक पेंशन",
          "pension", "S", "Uttarakhand", aMin=60, inc=48000),
    ],
    "Goa": [
        S("Griha Aadhar Scheme", "गृह आधार योजना",
          "₹1,500 monthly support to housewives/homemakers",
          "गृहिणियों को ₹1,500 मासिक सहायता",
          "wcd", "S", "Goa", g="F", occ=["homemaker"], aMin=18, inc=300000),
        S("Dayanand Social Security Scheme", "दयानंद सामाजिक सुरक्षा योजना",
          "₹2,500 monthly pension for elderly, disabled and single women",
          "वृद्धों, दिव्यांगों व एकल महिलाओं को ₹2,500 मासिक पेंशन",
          "pension", "S", "Goa", aMin=60),
    ],
    "Telangana_extra": [],
}
STATE_SCHEMES.pop("Telangana_extra")

# --------------------------------------------------------------------------
# 3. Centrally Sponsored Schemes implemented state-wise
#    (each state/UT runs its own application window / benefit delivery)
# --------------------------------------------------------------------------
TEMPLATES = [
    # (name_en, name_hi, benefit_en, benefit_hi, tag, elig)
    ("Indira Gandhi National Old Age Pension", "इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन",
     "₹200–₹500 monthly central pension plus state top-up for BPL elderly",
     "बीपीएल वृद्धों को केंद्र से ₹200–₹500 मासिक पेंशन व राज्य टॉप-अप",
     "pension", dict(aMin=60, bpl=True)),
    ("Indira Gandhi National Widow Pension", "इंदिरा गांधी राष्ट्रीय विधवा पेंशन",
     "₹300 monthly central pension plus state top-up for BPL widows",
     "बीपीएल विधवा महिलाओं को ₹300 मासिक केंद्रीय पेंशन व राज्य टॉप-अप",
     "pension", dict(g="F", aMin=40, wid=True, bpl=True)),
    ("Indira Gandhi National Disability Pension", "इंदिरा गांधी राष्ट्रीय दिव्यांग पेंशन",
     "₹300 monthly central pension plus state top-up for BPL disabled persons",
     "बीपीएल दिव्यांगजनों को ₹300 मासिक केंद्रीय पेंशन व राज्य टॉप-अप",
     "pension", dict(aMin=18, dis=True, bpl=True)),
    ("National Family Benefit Scheme", "राष्ट्रीय परिवार लाभ योजना",
     "₹20,000 one-time assistance on death of BPL family breadwinner",
     "बीपीएल परिवार के कमाऊ सदस्य की मृत्यु पर ₹20,000 एकमुश्त सहायता",
     "social", dict(aMin=18, aMax=59, bpl=True)),
    ("PM Awas Yojana – Gramin", "प्रधानमंत्री आवास योजना – ग्रामीण",
     "₹1.2–₹1.3 lakh assistance for building a pucca house in rural areas",
     "ग्रामीण क्षेत्रों में पक्का घर बनाने हेतु ₹1.2–₹1.3 लाख सहायता",
     "housing", dict(res="R", inc=200000, aMin=18)),
    ("PM Awas Yojana – Urban", "प्रधानमंत्री आवास योजना – शहरी",
     "Affordable housing subsidy through the Urban Local Body",
     "शहरी निकाय के माध्यम से किफायती आवास सब्सिडी",
     "housing", dict(res="U", inc=600000, aMin=18)),
    ("MGNREGA Job Card", "मनरेगा जॉब कार्ड",
     "100 days of guaranteed wage employment per rural household",
     "प्रति ग्रामीण परिवार 100 दिन की गारंटीड मजदूरी रोजगार",
     "worker", dict(res="R", aMin=18, occ=["worker", "unemployed", "farmer"])),
    ("NFSA Ration Card", "राष्ट्रीय खाद्य सुरक्षा राशन कार्ड",
     "Subsidised foodgrains (₹1–₹3/kg) for priority households",
     "प्राथमिकता परिवारों को ₹1–₹3 प्रति किलो रियायती खाद्यान्न",
     "food", dict(inc=250000)),
    ("Pre-Matric Scholarship (SC/ST/OBC/Minority)", "प्री-मैट्रिक छात्रवृत्ति",
     "Scholarship for school students of SC/ST/OBC/minority communities",
     "एससी/एसटी/ओबीसी/अल्पसंख्यक स्कूली छात्रों को छात्रवृत्ति",
     "edu", dict(occ=["student"], aMin=6, aMax=16,
                 cat=["sc", "st", "obc", "minority"], inc=250000)),
    ("Post-Matric Scholarship (SC/ST/OBC)", "पोस्ट-मैट्रिक छात्रवृत्ति",
     "Scholarship for SC/ST/OBC students studying class 11 and above",
     "कक्षा 11 व ऊपर पढ़ रहे एससी/एसटी/ओबीसी छात्रों को छात्रवृत्ति",
     "edu", dict(occ=["student"], aMin=16, aMax=32,
                 cat=["sc", "st", "obc"], inc=250000)),
    ("Ayushman Bharat PM-JAY (State)", "आयुष्मान भारत पीएम-जेएवाई (राज्य)",
     "₹5 lakh free annual family health cover via the State Health Agency",
     "राज्य स्वास्थ्य एजेंसी के माध्यम से ₹5 लाख वार्षिक निःशुल्क स्वास्थ्य कवर",
     "health", dict(inc=300000)),
    ("Janani Suraksha Yojana (State)", "जननी सुरक्षा योजना (राज्य)",
     "Cash assistance for institutional delivery via ASHA support",
     "आशा सहयोग से संस्थागत प्रसव पर नकद सहायता",
     "health", dict(g="F", preg=True, aMin=18, inc=300000)),
    ("PM Matru Vandana Yojana (State)", "प्रधानमंत्री मातृ वंदना योजना (राज्य)",
     "₹5,000 maternity benefit for first child through Anganwadi",
     "आंगनवाड़ी के माध्यम से पहले बच्चे पर ₹5,000 मातृत्व लाभ",
     "wcd", dict(g="F", preg=True, aMin=19)),
    ("ICDS Anganwadi Services", "आईसीडीएस आंगनवाड़ी सेवाएं",
     "Supplementary nutrition and health services for mothers and children",
     "माताओं व बच्चों को पूरक पोषण एवं स्वास्थ्य सेवाएं",
     "wcd", dict(g="F", preg=True)),
    ("PM POSHAN (Mid-Day Meal)", "पीएम पोषण (मध्याह्न भोजन)",
     "Free hot cooked meals for school children (classes 1–8)",
     "स्कूली बच्चों (कक्षा 1–8) को निःशुल्क पका हुआ भोजन",
     "edu", dict(occ=["student"], aMin=5, aMax=14)),
    ("Building & Construction Workers Welfare Board",
     "भवन एवं निर्माण श्रमिक कल्याण बोर्ड",
     "Pension, tool, marriage, maternity and education aid for registered workers",
     "पंजीकृत निर्माण श्रमिकों को पेंशन, औजार, विवाह, मातृत्व व शिक्षा सहायता",
     "worker", dict(occ=["worker"], aMin=18, aMax=60)),
    ("State Skill Development Mission", "राज्य कौशल विकास मिशन",
     "Free skill training with certification and placement support",
     "प्रमाणन व प्लेसमेंट सहायता सहित निःशुल्क कौशल प्रशिक्षण",
     "skill", dict(occ=["unemployed", "student", "worker"], aMin=15, aMax=45)),
    ("PM SVANidhi (Urban Local Body)", "पीएम स्वनिधि (शहरी निकाय)",
     "₹10,000–₹50,000 collateral-free loans for street vendors",
     "रेहड़ी-पटरी विक्रेताओं को ₹10,000–₹50,000 बिना गारंटी ऋण",
     "biz", dict(occ=["street_vendor"], res="U", aMin=18)),
    ("NRLM Self-Help Group (Aajeevika)", "एनआरएलएम स्वयं सहायता समूह (आजीविका)",
     "SHG membership with revolving fund and bank-linked credit for rural women",
     "ग्रामीण महिलाओं को एसएचजी सदस्यता, रिवॉल्विंग फंड व बैंक ऋण",
     "wcd", dict(g="F", res="R", aMin=18)),
    ("NULM Urban Livelihoods Mission", "राष्ट्रीय शहरी आजीविका मिशन",
     "Skill training, SHG support and subsidised loans for the urban poor",
     "शहरी गरीबों को कौशल प्रशिक्षण, एसएचजी सहायता व रियायती ऋण",
     "skill", dict(res="U", aMin=18,
                   occ=["unemployed", "worker", "street_vendor"], inc=300000)),
    ("Kisan Credit Card Saturation Drive", "किसान क्रेडिट कार्ड संतृप्ति अभियान",
     "KCC crop loans at subsidised interest through state agriculture dept",
     "राज्य कृषि विभाग के माध्यम से रियायती ब्याज पर केसीसी फसल ऋण",
     "agri", dict(occ=["farmer", "fisher"], aMin=18, aMax=75)),
    ("PM Fasal Bima Yojana (State Notified)", "प्रधानमंत्री फसल बीमा योजना (राज्य)",
     "Crop insurance for state-notified crops at nominal premium",
     "राज्य-अधिसूचित फसलों का नाममात्र प्रीमियम पर बीमा",
     "agri", dict(occ=["farmer"], aMin=18)),
    ("Agriculture Mechanisation Subsidy (SMAM)", "कृषि यंत्रीकरण अनुदान (एसएमएएम)",
     "40–80% subsidy on tractors, tillers and farm machinery",
     "ट्रैक्टर, टिलर व कृषि यंत्रों पर 40–80% अनुदान",
     "agri", dict(occ=["farmer"], aMin=18)),
    ("PM-KUSUM Solar Pump (State)", "पीएम-कुसुम सोलर पंप (राज्य)",
     "Subsidised solar irrigation pumps through state nodal agency",
     "राज्य नोडल एजेंसी के माध्यम से रियायती सोलर सिंचाई पंप",
     "agri", dict(occ=["farmer"], aMin=18)),
    ("PM Ujjwala Yojana (State)", "प्रधानमंत्री उज्ज्वला योजना (राज्य)",
     "Free LPG connection for poor women through district distributors",
     "जिला वितरकों के माध्यम से गरीब महिलाओं को निःशुल्क एलपीजी कनेक्शन",
     "wcd", dict(g="F", aMin=18, bpl=True)),
]


def build():
    schemes = []
    idx = 1

    for s in CENTRAL:
        s["id"] = "C%03d" % idx
        idx += 1
        schemes.append(s)

    for state, items in STATE_SCHEMES.items():
        for s in items:
            s["id"] = "S%03d" % idx
            idx += 1
            assert s["st"] == state, (s["n"], state)
            schemes.append(s)

    hi_map = dict(STATES)
    for (name_en, name_hi, ben_en, ben_hi, tag, elig) in TEMPLATES:
        for (st_en, st_hi) in STATES:
            s = S("%s – %s" % (name_en, st_en),
                  "%s – %s" % (name_hi, st_hi),
                  ben_en, ben_hi, tag, "CSS", st_en, **dict(elig))
            s["id"] = "T%04d" % idx
            idx += 1
            schemes.append(s)

    return schemes


def main():
    schemes = build()
    out = os.path.join(os.path.dirname(__file__), "..", "app", "schemes-data.js")
    payload = json.dumps(schemes, ensure_ascii=False, separators=(",", ":"))
    states = json.dumps(STATES, ensure_ascii=False, separators=(",", ":"))
    with open(out, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by generator/generate_schemes.py — do not edit by hand.\n")
        f.write("// %d schemes across India (Central + all States & UTs).\n" % len(schemes))
        f.write("const STATES_LIST=%s;\n" % states)
        f.write("const SCHEMES_DB=%s;\n" % payload)
    print("Wrote %d schemes to %s" % (len(schemes), os.path.abspath(out)))
    n_states = len(set(s["st"] for s in schemes if s["st"] != "ALL"))
    print("States/UTs covered with dedicated entries: %d" % n_states)


if __name__ == "__main__":
    main()
